import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';

let pool: Pool;
const users: string[] = [];
test.beforeAll(() => {
  const url = new URL(process.env.DATABASE_URL!);
  if (!['localhost', '127.0.0.1'].includes(url.hostname) || url.pathname !== '/paralax') throw new Error('Use apenas o banco local paralax para E2E.');
  pool = new Pool({ connectionString: process.env.DATABASE_URL });
});
test.afterEach(async () => { if (users.length) await pool.query('DELETE FROM "User" WHERE id = ANY($1::text[])', [users.splice(0)]); });
test.afterAll(async () => { await pool?.end(); });

test('sistema: criar → ordenar campos → prévia → salvar → recarregar → publicar → não listar → privatizar', async ({ page, browser }, testInfo) => {
  const suffix = randomUUID().replaceAll('-', '').slice(0, 10);
  const name = `Aether ${suffix}`;
  const problems: string[] = [];
  page.on('pageerror', error => problems.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && /hydration|didn't match/i.test(message.text())) problems.push(message.text()); });
  await page.goto('/cadastro');
  await page.getByLabel('Como podemos chamar você?').fill('Criadora de Aether');
  await page.getByLabel('Nome de usuário', { exact: true }).fill(`sistema_${suffix}`);
  await page.getByLabel('E-mail', { exact: true }).fill(`sistema_${suffix}@example.test`);
  await page.getByLabel('Senha', { exact: true }).fill('Uma-senha-de-teste-123!');
  const registration = page.waitForResponse(response => response.url().endsWith('/auth/register') && response.status() === 201);
  await page.getByRole('button', { name: 'Criar minha conta' }).click();
  users.push((await (await registration).json()).user.id);
  await expect(page).toHaveURL('/dashboard');
  await page.getByRole('link', { name: 'Sistemas', exact: true }).click();
  await page.getByRole('link', { name: 'Criar meu primeiro sistema' }).click();
  await page.getByRole('button', { name: 'Criar sistema', exact: true }).click();
  await expect(page.getByText('Use pelo menos 2 caracteres.')).toBeVisible();
  await page.getByLabel('Nome do sistema', { exact: true }).fill(name);
  await page.getByLabel('Descrição', { exact: true }).fill('Histórias entre ilhas flutuantes e estrelas.');

  await page.getByRole('button', { name: /^Atributos/ }).click();
  await page.getByRole('button', { name: 'Adicionar atributo' }).click();
  await page.getByLabel('Nome do atributo 1', { exact: true }).fill('Vontade');
  await page.getByLabel('Valor inicial do atributo 1').fill('3');
  await page.getByRole('button', { name: 'Adicionar atributo' }).click();
  await page.getByLabel('Nome do atributo 2', { exact: true }).fill('Agilidade');
  await page.getByLabel('Valor inicial do atributo 2').fill('2');
  await page.getByRole('button', { name: 'Mover atributo Agilidade para cima' }).click();
  await expect(page.getByLabel('Nome do atributo 1', { exact: true })).toHaveValue('Agilidade');
  await page.getByRole('button', { name: /^Perícias/ }).click();
  await page.getByRole('button', { name: 'Adicionar perícia' }).click();
  await page.getByLabel('Nome da perícia 1', { exact: true }).fill('Investigação');
  await page.getByLabel('Atributo da perícia 1').selectOption({ label: 'Vontade' });
  await page.getByRole('button', { name: /^Recursos/ }).click();
  await page.getByRole('button', { name: 'Adicionar recurso' }).click();
  await page.getByLabel('Nome do recurso 1', { exact: true }).fill('Energia');
  await page.getByLabel('Valor inicial do recurso 1').fill('5');
  await page.getByLabel('Máximo do recurso 1 (opcional)').fill('10');
  await expect(page.locator('.editor-preview-panel')).toContainText('5 / 10');
  await page.getByRole('button', { name: /^Dados/ }).click();
  await page.getByLabel('d100', { exact: true }).check();
  await page.getByLabel('Faces do dado personalizado').fill('3');
  await page.getByRole('button', { name: 'Adicionar dado', exact: true }).click();
  await expect(page.getByLabel('d3', { exact: true })).toBeChecked();
  const creating = page.waitForResponse(response => response.url().endsWith('/systems') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Criar sistema', exact: true }).click();
  const created = await creating; expect(created.status()).toBe(201); const system = await created.json();
  await expect(page).toHaveURL(`/sistemas/${system.id}/editar`);
  await expect(page.getByRole('status')).toHaveText('Salvo · versão 1');
  expect(system.definition.attributes.map((field: { name: string }) => field.name)).toEqual(['Agilidade', 'Vontade']);
  expect(system.definition.skills[0].attributeId).toBe(system.definition.attributes[1].id);
  await page.reload();
  await expect(page.getByLabel('Nome do sistema', { exact: true })).toHaveValue(name);
  await expect(page.locator('.editor-preview-panel')).toContainText('Investigação');
  await page.getByRole('button', { name: /^Atributos/ }).click();
  await page.screenshot({ path: `.artifacts/${testInfo.project.name}-sistema-editor.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);

  const anonymous = await browser.newContext({ viewport: page.viewportSize()!, isMobile: testInfo.project.name === 'mobile', hasTouch: testInfo.project.name === 'mobile' });
  try {
    const stranger = await anonymous.newPage();
    expect((await stranger.request.get(`http://localhost:3000/api/v1/systems/${system.id}`)).status()).toBe(404);
    await page.getByRole('button', { name: /^Informações gerais/ }).click();
    await page.getByLabel('Visibilidade', { exact: true }).selectOption('PUBLIC');
    await page.getByRole('button', { name: 'Salvar alterações' }).click();
    await expect(page.getByRole('status')).toHaveText('Salvo · versão 2');
    await stranger.goto(`http://localhost:3000/s/${system.id}`);
    await expect(stranger.getByRole('heading', { name, exact: true }).first()).toBeVisible();
    await expect(stranger.getByText('Energia', { exact: true })).toBeVisible();
    expect(await stranger.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await stranger.screenshot({ path: `.artifacts/${testInfo.project.name}-sistema-publico.png`, fullPage: true });
    await page.getByRole('link', { name: 'Seus sistemas', exact: true }).click();
    await page.getByRole('button', { name: 'Catálogo público' }).click();
    await page.getByLabel('Buscar sistemas').fill(suffix);
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
    await page.screenshot({ path: `.artifacts/${testInfo.project.name}-sistemas.png`, fullPage: true });
    await page.getByRole('button', { name: 'Meus sistemas' }).click();
    await page.getByRole('link', { name: 'Editar sistema', exact: true }).click();
    await page.getByLabel('Visibilidade', { exact: true }).selectOption('UNLISTED');
    await page.getByRole('button', { name: 'Salvar alterações' }).click();
    await expect(page.getByRole('status')).toHaveText('Salvo · versão 3');
    const catalog = await stranger.request.get(`http://localhost:3000/api/v1/systems/public?search=${suffix}`);
    expect((await catalog.json()).total).toBe(0);
    expect((await stranger.request.get(`http://localhost:3000/api/v1/systems/${system.id}`)).status()).toBe(200);
    await page.getByLabel('Visibilidade', { exact: true }).selectOption('PRIVATE');
    await page.getByRole('button', { name: 'Salvar alterações' }).click();
    await expect(page.getByRole('status')).toHaveText('Salvo · versão 4');
    expect((await stranger.request.get(`http://localhost:3000/api/v1/systems/${system.id}`)).status()).toBe(404);
  } finally { await anonymous.close(); }

  // Two open editors keep the second user's local edit after a conflict.
  const second = await page.context().newPage();
  await second.goto(`/sistemas/${system.id}/editar`);
  await expect(second.getByLabel('Nome do sistema')).toHaveValue(name);
  await page.getByLabel('Nome do sistema').fill(`${name} atualizado`);
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.getByRole('status')).toHaveText('Salvo · versão 5');
  await second.getByLabel('Nome do sistema').fill('Alteração local preservada');
  await second.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(second.getByRole('main').getByRole('alert')).toContainText('alterado em outra aba');
  await expect(second.getByLabel('Nome do sistema')).toHaveValue('Alteração local preservada');
  await expect(second.getByRole('button', { name: 'Salvar alterações' })).toBeDisabled();
  await second.getByLabel('Nome do sistema').fill('Rascunho após conflito');
  await expect(second.getByRole('main').getByRole('alert')).toContainText('alterado em outra aba');
  await expect(second.getByRole('button', { name: 'Carregar versão atual' })).toBeVisible();
  second.once('dialog', dialog => dialog.accept());
  await second.getByRole('button', { name: 'Carregar versão atual' }).click();
  await expect(second.getByLabel('Nome do sistema')).toHaveValue(`${name} atualizado`);
  await expect(second.getByRole('status')).toHaveText('Salvo · versão 5');
  await second.close();
  expect(problems).toEqual([]);
});
